export const macros = {
  "\\N": "\\mathbb{N}",
  "\\Nn": "\\mathbb{N}",
  "\\R": "\\mathbb{R}",
  "\\Rr": "\\mathbb{R}",
  "\\Z": "\\mathbb{Z}",
  "\\Zz": "\\mathbb{Z}",
  "\\Kk": "\\mathbb{K}",
  "\\Q": "\\mathbb{Q}",
  "\\Qq": "\\mathbb{Q}",
  "\\Cp": "\\mathbb{C}",
  "\\CC": "\\mathbb{C}",
  "\\Cc": "\\mathbb{C}",
  "\\RRe": "\\mathrm{Re}",
  "\\IIm": "\\mathrm{Im}",
  "\\C": "\\mathbb{C}",
  "\\im": "{\\mathrm{i}",
  "\\EX": "\\mathbb{E}(X)",
  "\\E": "\\mathbb {E}",
  "\\var": "\\mathrm{Var}",
  "\\V": "\\mathrm{V}",
  "\\Sol": "\\mathscr{S}",
  "\\PP": "\\mathrm{P}",
  "\\prob": "\\mathrm{P}",
  "\\OIJ": "($O$;$\\overrightarrow{\\imath}",
  "\\uu": "\\overrightarrow{u}",
  "\\vv": "\\overrightarrow{v}",
  "\\ww": "\\overrightarrow{w}",
  "\\Pn": "\\mathscr{P}",
  "\\Pnn": "\\mathscr{P}",
  "\\dx": "\\hspace{.6mm} \\mathrm{d}x",
  "\\dt": "\\hspace{.6mm} \\mathrm{d}t",
  "\\p": "\\mathrm{P}",
  "\\nd": "\\noindent}",
  "\\ssi": "si, et seulement si,}",
  "\\mq": "Montrer que}",
  "\\ep": "\\varepsilon}",
  "\\cad": "c'est-à-dire}",
  "\\1": "\\mathbf{1}",
  "\\dy": "\\hspace{.6mm} \\mathrm{d}y",
  "\\dz": "\\hspace{.6mm} \\mathrm{d}z",
  "\\du": "\\hspace{.6mm} \\mathrm{d}u",
  "\\dv": "\\hspace{.6mm} \\mathrm{d}v",
  "\\n": "_{n\\in\\N}",
  "\\nstar": "_{n\\in\\N^*}",
  "\\eq": "\\;\\Leftrightarrow\\;}",
  "\\impl": "\\;\\Rightarrow \\;}",
  "\\va": "variable aléatoire}",
  "\\vas": "variables aléatoires}",
  "\\lr": "\\longrightarrow}",
  "\\vide": "\\varnothing}",
  "\\dd": "\\textup{d}",
  "\\dlim": "\\displaystyle\\lim}",
  "\\vvvert": "\\vert\\!\\vert\\!\\vert", 
  "\\dpa": "\\frac{\\partial #1}{\\partial #2}",
  "\\dpsm": "\\frac{\\partial^2 #1}{\\partial #2 \\, \\partial #3}", // Macro pour dérivée mixte (3 arguments)
  "\\dpsp": "\\frac{\\partial^2 #1}{\\partial #2^2}"  
};